// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIfxdoGM5TWDVRjtfazvWZ9LnLlMnOuZ4',
    appId: '1:1005883564338:web:ad2b27b5bbd8c0993d772b',
    messagingSenderId: '1005883564338',
    projectId: 'yourpay-c5aaf',
    authDomain: 'yourpay-c5aaf.firebaseapp.com',
    storageBucket: 'yourpay-c5aaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6b_CgJzzbyGnwzUr6f8II2TrGref3PIs',
    appId: '1:1005883564338:android:842c9bda50a93c513d772b',
    messagingSenderId: '1005883564338',
    projectId: 'yourpay-c5aaf',
    storageBucket: 'yourpay-c5aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcDOqBARShc9W_r1Ug1moJVhEN67QUng4',
    appId: '1:1005883564338:ios:558990a354be4d443d772b',
    messagingSenderId: '1005883564338',
    projectId: 'yourpay-c5aaf',
    storageBucket: 'yourpay-c5aaf.firebasestorage.app',
    iosBundleId: 'com.example.yourpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcDOqBARShc9W_r1Ug1moJVhEN67QUng4',
    appId: '1:1005883564338:ios:558990a354be4d443d772b',
    messagingSenderId: '1005883564338',
    projectId: 'yourpay-c5aaf',
    storageBucket: 'yourpay-c5aaf.firebasestorage.app',
    iosBundleId: 'com.example.yourpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIfxdoGM5TWDVRjtfazvWZ9LnLlMnOuZ4',
    appId: '1:1005883564338:web:feffb7ddfd91f8e73d772b',
    messagingSenderId: '1005883564338',
    projectId: 'yourpay-c5aaf',
    authDomain: 'yourpay-c5aaf.firebaseapp.com',
    storageBucket: 'yourpay-c5aaf.firebasestorage.app',
  );
}
